baseurl = "https://elementalcodeworks.com/"
title        = "Elemental Codeworks"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
googleAnalytics = 'G-M4NV7CE2F8'

[params]
dateform        = "Jan 2, 2006"
dateformShort   = "Jan 2"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

# Subtitle for home
homeSubtitle = "I Help Create Digital Experiences"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Metadata mostly used in document's head
description = "Elemental CodeWorks is a single-employee Canadian Controlled Private Corporation based in Fredericton, New Brunswick, Canada that has provided digital experience consulting since 2004. I enjoy working on interesting projects, and engage with clients who share my interests and goals."
keywords = "homepage"
images = ["/img/header-logo.jpg"]

[taxonomies]
category = "blog"
tag      = "tags"
series   = "series"

[languages]
[languages.en]
title = "Elemental Codeworks"
subtitle = "I Help Create Digital Experiences"
keywords = "Digital Experiences, PHP, Drupal"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
readOtherPosts = "Read other posts"

customCSS = ["css/elementalcodeworks.css"]

[languages.en.params.logo]
logoText = "Elemental CodeWorks"
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
identifier = "contact"
name       = "Contact"
url        = "mailto:jake@elementalcodeworks.com"

[[menu.main]]
identifier = "privacy"
name       = "Privacy Policy"
url        = "/privacy.html"
